### ISSUE TITLE
Search API for Title/Medium/Artist

### ISSUE THREAD

**Issue by ameliatalkington** [ameliatalkington/ajax-project#1]
## 💰 Motivation

Art fanatics want to be able to search artworks by artist, title, and medium.

## 📐 Plan

Create an app that allows users to search for an artist, title, or medium.

## 🖼️ Wireframe

<img width="455" alt="Screen Shot 2021-02-22 at 5 17 19 PM" src="https://user-images.githubusercontent.com/52344883/108786868-d4dc8080-7531-11eb-81a6-f8dbd0540094.png">

## ✅ Task List

- [x] Create Header with title and dropdown arrow
- [x] Add background Image to body container
- [x] Add an input type search with label 'search'
- [x] Add appropriate CSS styling to get app to look like wireframe
- [x] Make the app compatible on both phone and desktop
- [x] Get results from the search and loop through the artist lists, title lists, and medium lists
- [x] Attach a suggested entry to the bottom of the searchbar 
- [x] Attach a max of up to 10 suggestions
