### ISSUE TITLE
When ‘enter’ is pressed during search

### ISSUE THREAD

**Issue by ameliatalkington** [ameliatalkington/ajax-project#2]
## 💰 Motivation

A page of search results is helpful for the user to find the piece of art they have in mind.

## 📐 Plan

Load a page of search results in the form of images.

## 🖼️ Wireframe

<img width="231" alt="Screen Shot 2021-02-22 at 5 52 49 PM" src="https://user-images.githubusercontent.com/52344883/108789114-cc3a7900-7536-11eb-961b-9bee4c12ed13.png">

## ✅ Task List

- [x] Create search result div in html
- [x] Add event listener to the 'enter' key
- [x] Under 'enter' event listener, load a new dom tree of the top 10 results for the search entry
- [x] Clear DOM tree between each new search
- [x] Add event listener to title in header which takes the use back to the main search page
