### ISSUE TITLE
User can view single image from search

### ISSUE THREAD

**Issue by ameliatalkington** [ameliatalkington/ajax-project#3]
## 💰 Motivation

An image and description is shown on the page.

## 📐 Plan

Upload the image and the description from entry selected.

## 🖼️ Wireframe

<img width="239" alt="Screen Shot 2021-02-22 at 5 54 21 PM" src="https://user-images.githubusercontent.com/52344883/108789216-04da5280-7537-11eb-81f0-39717f4416c1.png">

## ✅ Task List

- [x] Select all child nodes of $row and $entries
- [x] Add event listeners to the $row and $entries
- [x] Add a new div to html where selection will be rendered
- [x] When a suggestion/image is clicked show the selection div and hide the home and the search-results
- [x] Create a new function to add an image, a title, and a description to the page
- [x] Reset DOM on return to search page
