### ISSUE TITLE
User can favorite an image

### ISSUE THREAD

**Issue by ameliatalkington** [ameliatalkington/ajax-project#4]
## 💰 Motivation

Allow users to keep track of art pieces they like.

## 📐 Plan

Allow users to click on a heart icon to add an image to their 'favorites'

## 🖼️ Wireframe

<img width="234" alt="Screen Shot 2021-02-22 at 5 55 47 PM" src="https://user-images.githubusercontent.com/52344883/108789373-584ca080-7537-11eb-9b8d-15c9db38a9a3.png">
<img width="225" alt="Screen Shot 2021-02-22 at 5 55 53 PM" src="https://user-images.githubusercontent.com/52344883/108789377-5a166400-7537-11eb-9b01-6f0fcf6b3099.png">
<img width="458" alt="Screen Shot 2021-02-22 at 5 55 59 PM" src="https://user-images.githubusercontent.com/52344883/108789382-5be02780-7537-11eb-9feb-d8b70ade688e.png">

## ✅ Task List

- [x] Add a new div to the renderSelection() function that contains the title as well as a heart icon
- [x] Add an event listener to the heart icon
- [x] Add an event listener to the dropdown arrow
- [x] When arrow is clicked create a modal with the text content 'FAVORITES' that rests under the header
- [x] When the heart icon is clicked change the heart color to red
- [x] Create a userData object in the data.js file with the properties of entries and nextEntryNum
- [x] When heart icon is clicked add selection to local storage and update the entires and nextEntryNum
- [x] Create a new DOM of all of the entries (loop through entries)
- [x] When FAVORITES is clicked show entries page
- [x] When image in favorites is clicked show that entry with details
