### ISSUE TITLE
User can remove an image from favorites

### ISSUE THREAD

**Issue by ameliatalkington** [ameliatalkington/ajax-project#5]
## 💰 Motivation

Allow users to remove images they no longer like from their favorites

## 📐 Plan

Allow users to click on a heart icon again which makes a modal appear asking for removal confirmation.

## 🖼️ Wireframe

<img width="257" alt="Screen Shot 2021-02-22 at 5 59 11 PM" src="https://user-images.githubusercontent.com/52344883/108789526-afeb0c00-7537-11eb-88ab-678d9d91be6c.png">

## ✅ Task List

- [x] Add if/else to $like event listener. If heart is red, return to normal color, else turn to red.
- [x] If heart is red when clicked, add new modal to page asking for verification of un-favoriting
- [x] if the user clicks cancel close modal, if user clicks yes, remove that entry from data.entries and refresh the favorites page
